version: 0.1

phases:      
  install:
    commands:
      - echo ### installing maven ###
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk-headless
      - echo apt-get install -y maven      
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region=us-east-1)
  build:
    commands:
      - echo Build started on `date`      
      - echo Now we go with maven
      - mvn clean package      
      #- $(aws s3 cp user-data-service/target/user-data-service-*.jar s3://wc1-poc-spring-2019/ --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers --storage-class REDUCED_REDUNDANCY)
      - $(cp user-data-service/target/user-data-service-*.jar user-data-service/target/user-data-service.jar)
      - echo Building the Docker image...
      - $(docker ps)
      - $(docker build -t poc-tutorial .)
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Tagging image
      - $(docker tag poc-tutorial:latest 671124307843.dkr.ecr.us-east-1.amazonaws.com/poc-tutorial:latest)
      - echo Pushing the Docker image...
      - $(docker push 671124307843.dkr.ecr.us-east-1.amazonaws.com/poc-tutorial:latest)
artifacts:
  files:
    - user-data-service/target/user-data-service.jar